spring:
  main:
    web-application-type: none
    jackson:
      property-naming-strategy: SNAKE_CASE
app:
  threadPoolSize: 5
  maxRepoClone: 40
  cloneDir: "/tmp"
  github:
    baseUrl: "https://api.github.com"
    org: "${ORGANIZATION}"
    pat: "${GITHUB_TOKEN}"

logging:
  level:
    org: INFO
    org.devstat.gitdevstat: DEBUG
    org.devstat.gitdevstat.view.linesofcodebyauthor: TRACE
